create table app_users (
    id bigint generated by default as identity primary key,
    email varchar(180) not null unique,
    display_name varchar(120) not null,
    password_hash varchar(255) not null,
    role varchar(40) not null,
    active boolean not null,
    created_at timestamp with time zone not null
);

create table restaurants (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    address varchar(300) not null,
    delivery_fee numeric(10, 2) not null,
    accepting_orders boolean not null,
    owner_id bigint references app_users(id),
    created_at timestamp with time zone not null
);

create table menu_items (
    id bigint generated by default as identity primary key,
    restaurant_id bigint not null references restaurants(id),
    name varchar(160) not null,
    description varchar(500),
    price numeric(10, 2) not null,
    available boolean not null
);

create table food_orders (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references app_users(id),
    restaurant_id bigint not null references restaurants(id),
    status varchar(40) not null,
    subtotal numeric(10, 2) not null,
    delivery_fee numeric(10, 2) not null,
    total numeric(10, 2) not null,
    delivery_address varchar(300) not null,
    customer_note varchar(300),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references food_orders(id),
    menu_item_id bigint not null references menu_items(id),
    menu_name_snapshot varchar(160) not null,
    quantity integer not null,
    unit_price numeric(10, 2) not null,
    line_total numeric(10, 2) not null
);

create table payment_requests (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references food_orders(id),
    idempotency_key varchar(80) not null unique,
    amount numeric(10, 2) not null,
    currency varchar(3) not null,
    status varchar(40) not null,
    provider_reference varchar(160),
    created_at timestamp with time zone not null,
    authorized_at timestamp with time zone
);

create table delivery_tracking (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references food_orders(id),
    status varchar(40) not null,
    courier_name varchar(120),
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    updated_at timestamp with time zone not null
);

create index idx_food_orders_customer_created on food_orders(customer_id, created_at desc);
create index idx_menu_items_restaurant_available on menu_items(restaurant_id, available);
create index idx_delivery_tracking_order on delivery_tracking(order_id);
